In [60]:
import pandas as pd
import re

In [1]:
#files needed

In [89]:
folder = 'data/'
all_games = 'all_games_RWC2023.csv'
rubycology = 'Rugbycology_dataset_v2.csv'

In [119]:
rwc_2023_raw= pd.read_csv(folder+all_games)

# Clean the data if necessary

In [124]:
def clean_data_prepa(dataset):
    #look for missing data, there are none
    missing_values_sum = dataset.isna().sum() 
    print(missing_values_sum[missing_values_sum > 0] if any(missing_values_sum > 0) else 'No missing values')
    #look for spelling mistakes in teams name, all good
    team_A = list(dataset['Team A'].unique())
    team_B = list(dataset['Team B'].unique())
    teams = set(team_A + team_B)
    print(teams)
    dataset.Date = pd.to_datetime(dataset.Date)
    dataset[['Result A', 'Result B']] = dataset.apply(lambda row: pd.Series(['W' if row['Score A'] > row['Score B'] else ('D' if row['Score A'] == row['Score B'] else 'L'), 'W' if row['Score B'] > row['Score A'] else ('D' if row['Score B'] == row['Score A'] else 'L')]), axis=1)
    return dataset

In [126]:
rwc_clean = clean_data_prepa(rwc_2023_raw)
rwc_clean.head(10)

No missing values
{'Japan', 'Romania', 'New Zealand', 'Samoa', 'Australia', 'Uruguay', 'England', 'Wales', 'Georgia', 'Scotland', 'Italy', 'Fiji', 'Portugal', 'Argentina', 'France', 'Namibia', 'Tonga', 'Ireland', 'South Africa', 'Chile'}

,Date,Team A,Score A,Team B,Score B,Game ID,Knock-out,Possession A - Overall,Possession B - Overall,Possession A - 1st half,...,Penalties Conceded Own Half A,Penalties Conceded Own Half B,Penalties Conceded Opp Half A,Penalties Conceded Opp Half B,Yellow Cards A,Yellow Cards B,Red Cards A,Red Cards B,Result A,Result B
0,2023-10-28,New Zealand,11,South Africa,12,87881,Yes,60,40,63,...,4,6,1,4,1,2,1,0,L,W
1,2023-10-27,Argentina,23,England,26,87880,Yes,53,47,45,...,5,6,2,2,0,0,0,0,L,W
2,2023-10-21,England,15,South Africa,16,87879,Yes,56,44,52,...,4,4,7,4,0,0,0,0,L,W
3,2023-10-20,Argentina,6,New Zealand,44,87878,Yes,43,57,46,...,4,3,6,4,0,1,0,0,L,W
4,2023-10-15,France,28,South Africa,29,87877,Yes,60,40,59,...,2,5,4,1,0,1,0,0,L,W
5,2023-10-15,England,30,Fiji,24,87876,Yes,49,51,53,...,4,8,6,4,0,1,0,0,W,L
6,2023-10-14,Ireland,24,New Zealand,28,87875,Yes,55,45,51,...,4,8,6,2,0,2,0,0,L,W
7,2023-10-14,Wales,17,Argentina,29,87874,Yes,44,56,43,...,9,4,3,3,0,0,0,0,L,W
8,2023-10-08,Fiji,23,Portugal,24,87873,No,54,46,52,...,2,8,9,4,1,0,0,0,L,W
9,2023-10-08,Tonga,45,Romania,24,87872,No,57,43,52,...,5,2,4,6,1,1,0,0,W,L

In [106]:
#split the dataset in rows for team A and team B
def create_team_df(df, letter):
    #create a df from the original df for only team A or B(letter).
    #output:df with all variables without the A or B
    contains_letter = [col for col in rwc_clean.columns if re.search(r' {0}(?: |$)'.format(letter), col)]
    contains_letter = ['Date', 'Game ID', 'Knock-out'] + contains_letter
    team = df[contains_letter]
    for col in team:
        team.rename(columns={col:  re.sub(r' {0}(?= |$)'.format(letter), '', col)}, inplace=True)

    return team
  
team_A = create_team_df(rwc_clean, 'A')
team_B = create_team_df(rwc_clean, 'B')
teams = pd.concat([team_A, team_B], ignore_index=True)

teams.to_csv('team_split.csv', index=False)

print(teams.head(5))

        Date  Game ID Knock-out         Team  Score  Possession - Overall  \
0 2023-10-28    87881       Yes  New Zealand     11                    60
1 2023-10-27    87880       Yes    Argentina     23                    53
2 2023-10-21    87879       Yes      England     15                    56
3 2023-10-20    87878       Yes    Argentina      6                    43
4 2023-10-15    87877       Yes       France     28                    60

   Possession - 1st half  Possession - 2nd half  Tries  Conversions  ...  \
0                     63                     58      1            0  ...
1                     45                     59      2            2  ...
2                     52                     59      0            0  ...
3                     46                     40      0            0  ...
4                     59                     60      3            2  ...

   Rucks Successful  Total Rucks  Lineouts Successful  Lineouts Thrown  \
0               115          120                   20               22
1               109          111                    8                8
2                67           68                    7               10
3               115          119                   10               12
4               103          108                   12               12

   Scrums Successful  Scrums Total  Penalties Conceded Own Half  \
0                  2             2                            4
1                  6             7                            5
2                  3             7                            4
3                  4             4                            4
4                  5             9                            2

   Penalties Conceded Opp Half  Yellow Cards  Red Cards
0                            1             1          1
1                            2             0          0
2                            7             0          0
3                            6             0          0
4                            4             0          0

[5 rows x 34 columns]

/tmp/ipykernel_226060/2342304554.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team.rename(columns={col:  re.sub(r' {0}(?= |$)'.format(letter), '', col)}, inplace=True)
/tmp/ipykernel_226060/2342304554.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team.rename(columns={col:  re.sub(r' {0}(?= |$)'.format(letter), '', col)}, inplace=True)